// ── CASE REGISTRY ────────────────────────────────────────────
// To add a new case: create the JSX file, import it here, add one entry.

import Case01 from './Case01_CafeProfit.jsx'
import Case02 from './Case02_LaundryExpansion.jsx'
import Case03 from './Case03_FashionInventory.jsx'
import Case04 from './Case04_PhotographyUnitEcon.jsx'
import Case05 from './Case05_BakeryWorkingCapital.jsx'
import Case06 from './Case06_TutoringCAC_LTV.jsx'
import Case07 from './Case07_PrintROI.jsx'
import Case08 from './Case08_SparePartsBalanceSheet.jsx'
import Case09 from './Case09_FrozenFoodInvestment.jsx'
import Case10 from './Case10_LaundryOperatingLeverage.jsx'
import Case11 from './Case11_WarungPlatformDefense.jsx'
import Case12 from './Case12_BatikCapitalAllocation.jsx'

export const cases = [
  {
    id: 'case-01',
    slug: 'cafe-profit',
    number: '01',
    title: 'Why Is My Café Losing Profit?',
    subtitle: 'Revenue stayed flat but profit dropped by half — finding where the money went.',
    industry: 'Food & Beverage',
    firm: 'Small Business',
    framework: 'Contribution Margin + Menu Classification',
    decisionType: 'Pricing & Product Mix',
    difficulty: 'Beginner',
    region: 'Jakarta, Indonesia',
    readTime: '20 min read',
    accentColor: '#C4472A',
    component: Case01,
  },
  {
    id: 'case-02',
    slug: 'laundry-expansion',
    number: '02',
    title: 'Should I Open a Second Branch?',
    subtitle: 'A profitable laundry shop considers expansion — and discovers how much it actually needs to work.',
    industry: 'Services',
    firm: 'Small Business',
    framework: 'Break-Even Analysis + Scenario Modeling',
    decisionType: 'Expansion & Capital Allocation',
    difficulty: 'Beginner',
    region: 'Depok, Indonesia',
    readTime: '18 min read',
    accentColor: '#2A7AC4',
    component: Case02,
  },
  {
    id: 'case-03',
    slug: 'fashion-inventory',
    number: '03',
    title: 'Why Do I Keep Running Out of My Best Products?',
    subtitle: 'A thrift reseller discovers her revenue plateau is a self-inflicted inventory allocation problem.',
    industry: 'Retail / E-Commerce',
    firm: 'Small Business',
    framework: 'ABC Analysis + Inventory Turnover',
    decisionType: 'Inventory Allocation',
    difficulty: 'Beginner',
    region: 'Bandung, Indonesia',
    readTime: '18 min read',
    accentColor: '#7A2AC4',
    component: Case03,
  },
  {
    id: 'case-04',
    slug: 'photography-unit-economics',
    number: '04',
    title: 'Why Am I Always Busy But Never Saving Anything?',
    subtitle: 'A freelance photographer discovers his full calendar hides a real hourly rate of IDR 178,000 — half what he assumed.',
    industry: 'Creative Services',
    firm: 'Small Business',
    framework: 'Unit Economics',
    decisionType: 'Pricing & Time Allocation',
    difficulty: 'Beginner',
    region: 'Bandung, Indonesia',
    readTime: '18 min read',
    accentColor: '#8B5A2A',
    component: Case04,
  },
  {
    id: 'case-05',
    slug: 'bakery-working-capital',
    number: '05',
    title: 'My Biggest Order Almost Killed My Business',
    subtitle: 'A home bakery accepts the largest order of her career and runs out of cash within 20 days — despite being profitable.',
    industry: 'Food Production',
    firm: 'Small Business (UMKM)',
    framework: 'Working Capital Analysis',
    decisionType: 'Cash Flow Management',
    difficulty: 'Beginner',
    region: 'Surabaya, Indonesia',
    readTime: '17 min read',
    accentColor: '#C47A2A',
    component: Case05,
  },
  {
    id: 'case-06',
    slug: 'tutoring-cac-ltv',
    number: '06',
    title: "I'm Spending More Getting Students Than I Earn From Them",
    subtitle: 'An online tutoring founder discovers her ad channel produces low-LTV students while her best channel — referrals — is completely unfunded.',
    industry: 'Education',
    firm: 'Small Business',
    framework: 'CAC & LTV Analysis',
    decisionType: 'Customer Economics',
    difficulty: 'Beginner',
    region: 'Jakarta, Indonesia',
    readTime: '18 min read',
    accentColor: '#5A2A8B',
    component: Case06,
  },
  {
    id: 'case-07',
    slug: 'print-shop-roi',
    number: '07',
    title: 'Should I Buy the Machine or Keep Renting It?',
    subtitle: "A print shop owner evaluates a IDR 72M large-format printer — and learns why the salesperson's numbers were 41% overstated.",
    industry: 'Trade Services',
    firm: 'Small Business',
    framework: 'ROI + Payback Period',
    decisionType: 'Capital Expenditure',
    difficulty: 'Beginner',
    region: 'Semarang, Indonesia',
    readTime: '18 min read',
    accentColor: '#2A5C3F',
    component: Case07,
  },
  {
    id: 'case-08',
    slug: 'spare-parts-balance-sheet',
    number: '08',
    title: "I've Been Profitable for 8 Years. Why Won't the Bank Lend Me Money?",
    subtitle: 'A spare parts shop owner applies for a business loan and discovers his real net worth is IDR 23M — not the IDR 111M he believed.',
    industry: 'Retail / Auto Parts',
    firm: 'Small Business',
    framework: 'Balance Sheet Analysis',
    decisionType: 'Financing & Net Worth',
    difficulty: 'Beginner',
    region: 'Semarang, Indonesia',
    readTime: '20 min read',
    accentColor: '#2A4A8B',
    component: Case08,
  },
  {
    id: 'case-09',
    slug: 'frozen-food-investment',
    number: '09',
    title: 'Is the Platform Deal Worth It? A Frozen Food Producer Runs the Numbers',
    subtitle: 'Pak Hendro discovers that IDR 72M in Year 5 is worth only IDR 35.8M today — and how to value a platform contract across three possible futures.',
    industry: 'Food Production',
    firm: 'Small Business',
    framework: 'NPV + DCF + IRR + Scenario Analysis',
    decisionType: 'Capital Investment',
    difficulty: 'Beginner',
    region: 'Malang, Indonesia',
    readTime: '22 min read',
    accentColor: '#2A8B7A',
    component: Case09,
  },
  {
    id: 'case-10',
    slug: 'laundry-operating-leverage',
    number: '10',
    title: 'More Machines, More Risk — Or More Profit?',
    subtitle: "Pak Bimo's laundry profits swing IDR 16M between peak and slow season — and buying IDR 88M in new machines would turn a profitable business into an annual loss if demand doesn't grow.",
    industry: 'Laundry & Personal Services',
    firm: 'Small Business',
    framework: 'Operating Leverage Analysis',
    decisionType: 'Capital Expenditure / Capacity Investment',
    difficulty: 'Beginner',
    region: 'Bandung, Indonesia',
    readTime: '20 min read',
    accentColor: '#6A2A5A',
    component: Case10,
  },
  {
    id: 'case-11',
    slug: 'warung-platform-defense',
    number: '11',
    title: 'When the VC Money Comes to Town',
    subtitle: "Nadia's home-cook food platform has 65 curated cooks and real network effects — but a Series A startup is launching in her territory with IDR 400M in marketing. What can't money buy?",
    industry: 'Food Platform / Digital Marketplace',
    firm: 'Small Business',
    framework: 'Network Value Assessment + Competitive Moat Mapping',
    decisionType: 'Competitive Strategy',
    difficulty: 'Beginner',
    region: 'Surabaya, Indonesia',
    readTime: '21 min read',
    accentColor: '#2A6A8B',
    component: Case11,
  },
  {
    id: 'case-12',
    slug: 'batik-capital-allocation',
    number: '12',
    title: 'Three Doors for IDR 180 Million',
    subtitle: "Ibu Marlina has accumulated IDR 180M and three investment options: a second toko (24.96% ROIC), an online brand (214.7% ROIC), or an artisan workshop she has dreamed of for a decade (7.74% ROIC).",
    industry: 'Batik / Fashion Retail',
    firm: 'Small Business',
    framework: 'ROIC Comparison + Competitive Moat Assessment',
    decisionType: 'Capital Allocation',
    difficulty: 'Beginner',
    region: 'Solo, Indonesia',
    readTime: '22 min read',
    accentColor: '#8B6A2A',
    component: Case12,
  },
]

export function getCaseBySlug(slug) {
  return cases.find(c => c.slug === slug) ?? null
}
