// ── PRELIM REGISTRY ───────────────────────────────────────────
// Foundation modules that build vocabulary before the case studies.
// To add a new prelim: create the JSX file, import it here, add one entry.

import PreA1 from './PreA1_RevenueProfitCash.jsx'
import PreB1 from './PreB1_FixedVsVariable.jsx'
import PreA3 from './PreA3_Margins.jsx'
import PreA4 from './PreA4_WorkingCapital.jsx'
import PreB2 from './PreB2_UnitEconomics.jsx'
import PreB3 from './PreB3_CAC_LTV.jsx'
import PreB4 from './PreB4_BreakEven.jsx'
import PreA5 from './PreA5_BalanceSheet.jsx'
import PreB5 from './PreB5_ROI.jsx'
import PreC1 from './PreC1_TimeValueOfMoney.jsx'
import PreC2 from './PreC2_NPV_DCF.jsx'
import PreC3 from './PreC3_IRR_MOIC.jsx'
import PreC4 from './PreC4_ScenarioAnalysis.jsx'

export const prelims = [
  {
    id: 'pre-a1',
    slug: 'revenue-profit-cash',
    moduleId: 'A1',
    module: 'Module A · The Language of Money',
    title: 'Revenue vs Profit vs Cash',
    subtitle: 'The three numbers every business owner confuses — and why mixing them up is dangerous.',
    concept: 'Income Statement Basics',
    difficulty: 'Foundation',
    readTime: '10 min read',
    accentColor: '#2A7AC4',
    component: PreA1,
    unlocksCase: ['Case 01', 'Case 02'],
  },
  {
    id: 'pre-b1',
    slug: 'fixed-vs-variable-costs',
    moduleId: 'B1',
    module: 'Module B · How Businesses Create Value',
    title: 'Fixed vs Variable Costs',
    subtitle: 'The cost distinction that underlies every pricing, break-even, and expansion decision.',
    concept: 'Cost Structure',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#2AC47A',
    component: PreB1,
    unlocksCase: ['Case 01', 'Case 02', 'Case 03'],
  },
  {
    id: 'pre-a3',
    slug: 'margins',
    moduleId: 'A3',
    module: 'Module A · The Language of Money',
    title: 'Gross, Contribution & EBITDA Margins',
    subtitle: 'Three margin concepts, when to use each, and why your most popular item might not be your most profitable.',
    concept: 'Margin Analysis',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#C4A02A',
    component: PreA3,
    unlocksCase: ['Case 01', 'Case 02'],
  },
  {
    id: 'pre-b4',
    slug: 'break-even',
    moduleId: 'B4',
    module: 'Module B · How Businesses Create Value',
    title: 'Break-Even Analysis',
    subtitle: 'How many cups, kg, or orders until a business stops losing money — and why this is the first question to ask.',
    concept: 'Break-Even',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#C4472A',
    component: PreB4,
    unlocksCase: ['Case 01', 'Case 02'],
  },
  {
    id: 'pre-b2',
    slug: 'unit-economics',
    moduleId: 'B2',
    module: 'Module B · How Businesses Create Value',
    title: 'Unit Economics',
    subtitle: 'What one sale, one job, or one customer actually earns — and why a full calendar is not the same as a profitable business.',
    concept: 'Unit Economics',
    difficulty: 'Foundation',
    readTime: '11 min read',
    accentColor: '#8B5A2A',
    component: PreB2,
    unlocksCase: ['Case 04'],
  },
  {
    id: 'pre-a4',
    slug: 'working-capital',
    moduleId: 'A4',
    module: 'Module A · The Language of Money',
    title: 'Working Capital',
    subtitle: 'The cash a business needs to fund the gap between paying costs and collecting from customers — and why profitable businesses run out of cash.',
    concept: 'Working Capital & Cash Flow',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#C47A2A',
    component: PreA4,
    unlocksCase: ['Case 05'],
  },
  {
    id: 'pre-b3',
    slug: 'cac-ltv',
    moduleId: 'B3',
    module: 'Module B · How Businesses Create Value',
    title: 'CAC & LTV',
    subtitle: 'What it costs to acquire a customer vs. what that customer is worth — and why not all customers are equally valuable.',
    concept: 'Customer Acquisition & Lifetime Value',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#5A2A8B',
    component: PreB3,
    unlocksCase: ['Case 06'],
  },
  {
    id: 'pre-a5',
    slug: 'balance-sheet',
    moduleId: 'A5',
    module: 'Module A · The Language of Money',
    title: 'The Balance Sheet',
    subtitle: 'What your business owns, what it owes, and the difference — your actual net worth, not what you feel it is.',
    concept: 'Assets, Liabilities & Owner\'s Equity',
    difficulty: 'Foundation',
    readTime: '13 min read',
    accentColor: '#2A4A8B',
    component: PreA5,
    unlocksCase: ['Case 08'],
  },
  {
    id: 'pre-b5',
    slug: 'roi-payback',
    moduleId: 'B5',
    module: 'Module B · How Businesses Create Value',
    title: 'ROI & Payback Period',
    subtitle: 'Whether a capital investment earns back more than it costs — and how to stress-test the salesperson\'s numbers.',
    concept: 'Return on Investment',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#2A5C3F',
    component: PreB5,
    unlocksCase: ['Case 07'],
  },
  {
    id: 'pre-c1',
    slug: 'time-value-of-money',
    moduleId: 'C1',
    module: 'Module C · Value Over Time',
    title: 'Time Value of Money',
    subtitle: "Why a rupiah today is worth more than a rupiah tomorrow — and how to compare cash flows that arrive at different points in time.",
    concept: 'Time Value & Discounting',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#8B2A4A',
    component: PreC1,
    unlocksCase: ['Case 09'],
  },
  {
    id: 'pre-c2',
    slug: 'npv-dcf',
    moduleId: 'C2',
    module: 'Module C · Value Over Time',
    title: 'NPV & Discounted Cash Flow',
    subtitle: 'How to translate a stream of future cash flows into a single present-day verdict — and use it to say yes or no to an investment.',
    concept: 'Net Present Value',
    difficulty: 'Foundation',
    readTime: '13 min read',
    accentColor: '#4A8B2A',
    component: PreC2,
    unlocksCase: ['Case 09'],
  },
  {
    id: 'pre-c3',
    slug: 'irr-moic',
    moduleId: 'C3',
    module: 'Module C · Value Over Time',
    title: 'IRR & MOIC',
    subtitle: 'Two ways to measure investment return — the annualised rate and the raw cash multiple — and why the same MOIC can hide very different IRRs.',
    concept: 'Return Metrics',
    difficulty: 'Foundation',
    readTime: '12 min read',
    accentColor: '#8B8B2A',
    component: PreC3,
    unlocksCase: ['Case 09'],
  },
  {
    id: 'pre-c4',
    slug: 'scenario-analysis',
    moduleId: 'C4',
    module: 'Module C · Value Over Time',
    title: 'Scenarios & Probability Weighting',
    subtitle: 'How to build optimistic, base, and pessimistic futures — and combine them into a single expected value that accounts for uncertainty honestly.',
    concept: 'Scenario Analysis',
    difficulty: 'Foundation',
    readTime: '13 min read',
    accentColor: '#4A2A8B',
    component: PreC4,
    unlocksCase: ['Case 09'],
  },
]

export function getPrelimBySlug(slug) {
  return prelims.find(p => p.slug === slug) ?? null
}
