import ROIPaybackCalc from './calculators/ROIPaybackCalc.jsx'

const PreB5 = () => {
  return (
    <div className="case-study">
      <header className="case-header">
        <span className="case-number">Foundation · Module B5</span>
        <h1>ROI &amp; Payback Period</h1>
        <div className="case-meta">
          Module B: How Businesses Create Value &bull; Whether a capital investment earns back more than it costs
        </div>
      </header>

      {/* ── SECTION 1 ── */}
      <section>
        <h2>1. Why This Concept Matters</h2>
        <div className="content">
          <p>
            <strong>Adi</strong> (33) is a freelance event photographer in Surabaya. Drone shots have
            become popular for wedding and corporate events — wide aerials, dramatic establishing
            shots, coverage that ground-level cameras cannot capture.
          </p>
          <p>
            Adi currently rents a drone from a supplier for <strong>IDR 500,000 per event</strong>.
            He does about 6 drone events per month. That is IDR 3,000,000 per month in rental costs.
            He charges clients IDR 1,200,000 for the drone package — so he earns
            IDR 700,000 profit per drone event (before his own time).
          </p>
          <p>
            A photography equipment shop offers him a professional event drone for
            <strong> IDR 18,000,000</strong>. The salesperson says: "You spend IDR 3 million a month
            renting — you'll pay this off in 6 months." Adi is tempted. But he has never done
            a formal investment analysis. He does not know what the purchase actually saves him,
            whether 6 months is accurate, or what happens if he has fewer drone bookings next year.
          </p>
          <div className="highlight-box">
            <strong>What Is ROI and Payback Period?</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <strong>ROI (Return on Investment)</strong> measures how much you get back relative to
              what you put in — expressed as a percentage.
              <br /><br />
              <strong>Payback Period</strong> measures how long it takes to recover the initial investment
              from the returns it generates — expressed in months or years.
              <br /><br />
              Together they answer the capital allocation question: <em>"Is this investment worth
              making, and how quickly do I get my money back?"</em>
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 2 ── */}
      <section>
        <h2>2. The Concept Defined</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>Return on Investment (ROI)</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <strong>ROI = (Net Gain from Investment ÷ Cost of Investment) × 100%</strong>
              <br /><br />
              <em>Net Gain</em> = total benefit generated by the investment minus the investment cost.
              <br /><br />
              Example: you spend IDR 18M on a drone. Over 3 years it saves IDR 108M in rental costs
              (IDR 3M/month × 36 months) minus IDR 3.6M in maintenance. Net gain = IDR 108M − IDR 3.6M − IDR 18M =
              IDR 86.4M. ROI = IDR 86.4M ÷ IDR 18M × 100% = <strong>480%</strong>.
              <br /><br />
              ROI can be calculated over any time horizon (1 year, 3 years, 5 years). Always state
              the time period alongside the ROI figure — 480% over 3 years is very different from
              480% over 30 years.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Simple Payback Period</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              <strong>Payback Period = Investment Cost ÷ Monthly Net Benefit</strong>
              <br /><br />
              The payback period answers: "How many months until I have recovered what I spent?"
              After the payback period, every month of benefit is pure return.
              <br /><br />
              The payback period is a quick sanity check, not a full analysis. It ignores benefits
              that arrive after payback, which is why a purchase with a 3-month payback and
              10-year useful life is far more attractive than one stated payback period implies.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Opportunity Cost of Capital</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Money spent on an investment is money that cannot be used for anything else. If Adi
              spends IDR 18M on a drone, that IDR 18M is no longer available for marketing, equipment
              upgrades, a second camera, or a savings cushion. The opportunity cost is the value of
              the next best alternative use of that money.
              <br /><br />
              For a small business owner, the simplest benchmark is the annual return available from
              a savings account or time deposit — typically 5–7% per year in Indonesia. Any investment
              should beat this hurdle rate, or the money is better left in savings.
            </p>
          </div>

          <p><strong>ROI Analysis Components:</strong></p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Component</th>
                <th>Description</th>
                <th>Common Mistake</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Investment Cost</strong></td>
                <td>Total upfront cash outlay</td>
                <td>Forgetting installation, setup, training costs</td>
              </tr>
              <tr>
                <td><strong>Ongoing Costs</strong></td>
                <td>Maintenance, insurance, consumables</td>
                <td>Ignoring these entirely</td>
              </tr>
              <tr>
                <td><strong>Monthly Benefit</strong></td>
                <td>Savings or additional profit generated</td>
                <td>Using best-case volume instead of realistic volume</td>
              </tr>
              <tr>
                <td><strong>Useful Life</strong></td>
                <td>How long the asset generates benefit</td>
                <td>Assuming infinite life — depreciation is real</td>
              </tr>
              <tr>
                <td><strong>Payback Period</strong></td>
                <td>Investment ÷ monthly net benefit</td>
                <td>Not stress-testing against lower-volume scenarios</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ── SECTION 3 ── */}
      <section>
        <h2>3. The Common Mistake</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>Mistake 1 — Ignoring Ongoing Costs</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              The salesperson's calculation: IDR 3M/month rental cost ÷ IDR 18M purchase = 6-month
              payback. Clean and appealing. But it omits the costs Adi will now bear as the owner:
              drone insurance (IDR 150K/month), battery replacement cycles (IDR 200K/month amortised),
              firmware updates and calibration (IDR 50K/month). These IDR 400K/month in ongoing costs
              reduce the net monthly benefit from IDR 3M to IDR 2.6M. Payback moves from 6.0 to 6.9 months.
              Not dramatic, but real — and more complex equipment can have much higher ongoing costs.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Mistake 2 — Using Current Volume Without Stress-Testing</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Adi currently does 6 drone events per month. The payback calculation assumes 6 events
              per month forever. But what if next year he does only 3 drone events per month? The
              rental savings halve. Payback extends. The investment that looked compelling at 6.9
              months may take 14+ months at half volume. Volume assumptions must always be tested
              against a conservative scenario. If the investment is still attractive at 50–70% of
              current volume, it is robust. If not, the decision depends entirely on volume staying
              high — a risky bet.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Mistake 3 — Forgetting the Opportunity Cost</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              IDR 18,000,000 spent on a drone is IDR 18,000,000 not available for a backup camera
              body (which might generate more revenue), a marketing campaign, or an emergency reserve.
              Before making any capital commitment, ask: "Of all the ways I could deploy this
              IDR 18M, is this the highest-ROI use?" The answer may still be yes — but the question
              should be asked explicitly, not assumed.
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 4 ── */}
      <section>
        <h2>4. Worked Example — Adi's Drone Investment Analysis</h2>
        <div className="content">
          <div className="calculation">
{`Adi's Drone Purchase Analysis

─── INVESTMENT COST ───
Purchase price (drone + controller + case):   IDR  18,000,000
Setup & calibration (one-time):               IDR     300,000
Initial accessories (extra batteries, ND filters): IDR   800,000
Total investment:                             IDR  19,100,000

─── MONTHLY BENEFIT (at current volume: 6 events/month) ───
Rental cost saved per event: IDR 500,000
Events per month: 6
Gross monthly saving: 6 × IDR 500,000             = IDR  3,000,000

─── MONTHLY ONGOING COSTS (new ownership costs) ───
Drone insurance:                                   IDR   (150,000)
Battery amortisation (replace every 18 months      IDR   (167,000)
  × IDR 3M cost ÷ 18):
Repair reserve (1% of purchase/month):             IDR   (180,000)
Total monthly ongoing costs:                       IDR   (497,000)

Net monthly benefit: IDR 3,000,000 − IDR 497,000  = IDR  2,503,000

─── PAYBACK PERIOD ───
Payback = IDR 19,100,000 ÷ IDR 2,503,000/month   = 7.6 months

(Salesperson's quoted payback: 6.0 months — 27% understated)

─── ROI ANALYSIS (3-year horizon, assuming 5-year useful life) ───
3-year net benefit: IDR 2,503,000 × 36 months      = IDR 90,108,000
Total investment:                                  = IDR (19,100,000)
3-year net gain:                                   = IDR 71,008,000
3-year ROI: IDR 71,008,000 ÷ IDR 19,100,000 × 100 = 372%

─── STRESS TEST: What if drone events drop to 3/month? ───
Gross monthly saving: 3 × IDR 500,000              = IDR  1,500,000
Monthly ongoing costs:                             = IDR   (497,000)
Net monthly benefit at 3 events:                   = IDR  1,003,000

Payback at 3 events/month:
  IDR 19,100,000 ÷ IDR 1,003,000                   = 19.0 months

3-year ROI at 3 events/month:
  (IDR 1,003,000 × 36 − IDR 19,100,000) / IDR 19,100,000 × 100
  = (IDR 36,108,000 − IDR 19,100,000) / IDR 19,100,000 × 100
  = 89%  ← still positive, but much lower

─── DECISION SUMMARY ───
At 6 events/month:  payback 7.6 months, 3yr ROI 372%  → Attractive ✓
At 3 events/month:  payback 19.0 months, 3yr ROI 89%  → Marginal but positive ✓
Minimum breakeven volume: IDR 497,000 ÷ IDR 500,000 = 1 event/month to cover ownership costs
Breakeven volume to justify investment in 2 years: IDR 19,100,000/24 + IDR 497,000 = IDR 1,293,666
  → requires at least 3 events/month (IDR 1,500,000 net) to pay off in 2 years`}
          </div>

          <p style={{ marginTop: '20px' }}><strong>Summary Comparison — Rent vs. Buy:</strong></p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Scenario</th>
                <th>Monthly Events</th>
                <th>Payback Period</th>
                <th>3-Year ROI</th>
                <th>Verdict</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Base case</td>
                <td>6</td>
                <td>7.6 months</td>
                <td>372%</td>
                <td>Strong buy</td>
              </tr>
              <tr>
                <td>Moderate drop</td>
                <td>4</td>
                <td>12.0 months</td>
                <td>202%</td>
                <td>Good buy</td>
              </tr>
              <tr>
                <td>Stress case</td>
                <td>3</td>
                <td>19.0 months</td>
                <td>89%</td>
                <td>Marginal — consider</td>
              </tr>
              <tr>
                <td>Severe drop</td>
                <td>1</td>
                <td>38.0 months</td>
                <td>−4%</td>
                <td>Do not buy</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ── SECTION 5 ── */}
      <section>
        <h2>5. How This Shows Up in the Cases</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>Case 07 — Pak Doni's Print Shop</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Doni outsources large-format printing at IDR 45,000/m² and sells to clients at
              IDR 75,000/m². A supplier offers a printer for IDR 72,000,000. His in-house
              production cost would fall to IDR 12,000/m², lifting gross profit from IDR 30K
              to IDR 63K per m². At 380 m²/month, the machine pays back in 10.8 months and
              delivers a 456% 5-year ROI. But the salesperson's calculation overstated monthly
              savings by 41% by omitting maintenance, consumables, and electricity. The case
              shows how to build a complete cost model and stress-test the payback against
              volume scenarios — exactly the analysis Adi needed.
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 6 ── */}
      <section>
        <h2>6. Beginner Practitioner's Notes</h2>
        <div className="content">
          <div className="highlight-box">
            <strong>Always Ask What Happens at Half Volume</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              The most important stress test for any capital investment is: if the volume of work
              that justifies this purchase dropped by 50%, would the investment still be worthwhile?
              If yes, the purchase is robust. If no — if it only makes sense when everything goes
              perfectly — it is a bet on the future, not an investment with a margin of safety.
              Build the conservative case before committing.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Payback Period Is a Risk Measure, Not a Profit Measure</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              A short payback period means less time exposed to the risk that circumstances change
              before you recover your investment. A 3-month payback is lower risk than a 30-month
              payback, even if the 30-month investment has a higher eventual ROI. In fast-changing
              industries — technology, fashion, food trends — always bias toward shorter payback
              periods. Equipment with a 5-year payback in a market that changes every 2 years is
              likely to become obsolete before it earns back its cost.
            </p>
          </div>
          <div className="highlight-box">
            <strong>Include Every Cost the Salesperson Left Out</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              Equipment salespeople present the best-case scenario: full utilisation, no maintenance
              problems, perfect volume. Your job is to complete the picture. For any equipment purchase,
              ask: What does it cost to insure? What breaks and how often? What consumables does it
              need? What does it cost to train staff on it? What happens if it needs servicing for
              2 weeks? Add a 10–15% contingency to your ongoing cost estimate for costs you
              have not yet encountered.
            </p>
          </div>
          <div className="highlight-box">
            <strong>ROI Compares Investment, Not Just Savings</strong>
            <p style={{ marginTop: '8px', fontSize: '14px' }}>
              When evaluating multiple capital options, compare their ROI — not just their absolute
              savings. A IDR 5M investment that saves IDR 2M/year (40% ROI) is better than a
              IDR 20M investment that saves IDR 4M/year (20% ROI), because the first deployment of
              capital is twice as efficient. If you have limited capital to invest, allocate it
              first to the highest-ROI option, then to the next-highest, until the capital runs out
              or the marginal ROI falls below your hurdle rate.
            </p>
          </div>
        </div>
      </section>


      {/* ── SECTION 7 ── */}
      <section>
        <h2>7. Try It — Interactive Calculator</h2>
        <div className="content">
          <p>
            Enter the investment size and annual profit to see whether the return clears the 8% bank hurdle — and by how much.
          </p>
          <ROIPaybackCalc />
        </div>
      </section>

    </div>
  )
}

export default PreB5
